// <auto-generated />
using ArtStudio.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtStudio.Server.Data.Migrations
{
    [DbContext(typeof(StudioDbContext))]
    [Migration("20261007125245_ReadyToPost")]
    partial class ReadyToPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ArtStudio.Server.Domain.BlockedArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("BlockedArtists");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.BuildingBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuildingBlocks");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.GeneratedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromptSetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationJobId");

                    b.HasIndex("PromptSetId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.GenerationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentComfyPromptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptSetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromptSetId");

                    b.HasIndex("Status", "QueuePosition");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.PickedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneratedImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromptSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedImageId");

                    b.HasIndex("PromptSetId", "GeneratedImageId")
                        .IsUnique();

                    b.ToTable("Picks");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.PromptSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviantArtAuthor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviantArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadyToPostAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviationId");

                    b.ToTable("PromptSets");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.StudioSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComfyServerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviantArtClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviantArtUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnJobDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnQueueEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDeviantArtClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDeviantArtRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("QueuePaused")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.GeneratedImage", b =>
                {
                    b.HasOne("ArtStudio.Server.Domain.GenerationJob", null)
                        .WithMany()
                        .HasForeignKey("GenerationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtStudio.Server.Domain.PromptSet", null)
                        .WithMany("Images")
                        .HasForeignKey("PromptSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.GenerationJob", b =>
                {
                    b.HasOne("ArtStudio.Server.Domain.PromptSet", "PromptSet")
                        .WithMany("Jobs")
                        .HasForeignKey("PromptSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptSet");
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.PickedImage", b =>
                {
                    b.HasOne("ArtStudio.Server.Domain.GeneratedImage", null)
                        .WithMany()
                        .HasForeignKey("GeneratedImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtStudio.Server.Domain.PromptSet", null)
                        .WithMany("Picks")
                        .HasForeignKey("PromptSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtStudio.Server.Domain.PromptSet", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Jobs");

                    b.Navigation("Picks");
                });
#pragma warning restore 612, 618
        }
    }
}
